version: "3.8"
services:

  personal-website:
    image: personal-website:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: personal-website
    restart: always
    networks:
      - main_network
    # ports:
    #   - 127.0.0.1:3001:3001
    env_file:
      - ./.env

networks:
  main_network:
    name: main_network